//! TDD tests for CXA-F024 — Test-to-AC Traceability Matrix (TEST seam).
//!
//! AC2: "After TEST completes verification, the matrix is auto-generated by
//! matching test descriptions/assertions against the ticket's acceptance
//! criteria text using keyword + fuzzy (Levenshtein ≤ 0.3) overlap scoring."
//!
//! The per-AC coverage the matrix renders is written by
//! [`RunTestUseCase::execute`] when it applies the TEST agent's verdicts to
//! the shipped tickets' test cases. Today that match is EXACT TEXT ONLY
//! (`parsing::TestVerdict.ac`: "The system matches it word-for-word"), so the
//! fuzzy/keyword tests below fail until the scoring exists. Pure fixtures: an
//! in-memory store and a canned engine — no IO, no network, no server.

#[cfg(test)]
mod tdd_tests {
    use crate::config::Config;
    use crate::ports::outbound::{
        AgentEnginePort, AgentOutcome, AgentRequest, SandboxStatus, StateStorePort,
    };
    use crate::state::ProjectState;
    use crate::use_cases::RunTestUseCase;
    use crate::PortError;
    use coxagent_domain::ticket::TestCaseStatus;
    use coxagent_domain::{Complexity, Priority, Role, Status, Ticket, TicketId, TicketType};
    use std::path::PathBuf;
    use std::sync::{Arc, Mutex};

    #[derive(Default)]
    struct MemStore {
        state: Mutex<ProjectState>,
    }

    #[async_trait::async_trait]
    impl StateStorePort for MemStore {
        async fn load(&self) -> Result<ProjectState, PortError> {
            Ok(self.state.lock().expect("lock").clone())
        }
        async fn save(&self, s: &ProjectState) -> Result<(), PortError> {
            s.validate().map_err(PortError::Corrupt)?;
            *self.state.lock().expect("lock") = s.clone();
            Ok(())
        }
    }

    struct Canned(String);

    #[async_trait::async_trait]
    impl AgentEnginePort for Canned {
        fn id(&self) -> &'static str {
            "canned"
        }
        async fn run(&self, _r: AgentRequest) -> Result<AgentOutcome, PortError> {
            Ok(AgentOutcome {
                stdout: self.0.clone(),
                stderr: String::new(),
                exit_code: Some(0),
                usage: None,
                trace: String::new(),
                session_id: None,
                sandbox: SandboxStatus::default(),
                engine: String::new(),
                model: String::new(),
                attempts: Vec::new(),
            })
        }
    }

    /// The ticket's acceptance criterion the TEST agent is verifying.
    const AC: &str = "the bug can no longer be reproduced on a fresh checkout";
    /// The ticket's second criterion — never verdicted, must stay NOT TESTED.
    const AC_OTHER: &str = "the fix ships with a regression test";

    /// A bug in `Fixed` with synced test cases: the JUST SHIPPED state the
    /// TEST pass verifies against.
    fn fixed_bug_state() -> ProjectState {
        let mut t = Ticket::new(
            TicketId::new("BUG-F024").expect("valid id"),
            TicketType::Bug,
            "crash on save",
            "the app crashes when saving an empty record",
            Priority::High,
            Complexity::Small,
            false,
        )
        .expect("valid ticket");
        t.set_acceptance_criteria(vec![AC.to_owned(), AC_OTHER.to_owned()]);
        t.ensure_test_cases_from_acceptance();
        t.claim(Role::DevBug, "dev@host", "2026-08-20T00:00:00Z")
            .expect("unclaimed bug is claimable");
        t.transition_to(Role::DevBug, Status::Fixed)
            .expect("dev may mark a claimed bug fixed");
        ProjectState {
            tickets: vec![t],
            ..ProjectState::default()
        }
    }

    fn uc(store: Arc<MemStore>, out: &str) -> RunTestUseCase<MemStore, Canned> {
        RunTestUseCase::new(
            store,
            Arc::new(Canned(out.to_owned())),
            Config::default(),
            PathBuf::from("/tmp"),
        )
    }

    /// Run one TEST verification pass whose only output is a single `passed`
    /// verdict for `verdict_ac` (the free-form criterion text the engine
    /// emitted), then return the resulting status of the REAL criterion's
    /// test case.
    async fn case_status_after_verdict(verdict_ac: &str) -> TestCaseStatus {
        let store = Arc::new(MemStore {
            state: Mutex::new(fixed_bug_state()),
        });
        let out = format!(
            r#"{{"bugs": [], "verdicts": [{{"ac": "{verdict_ac}", "passed": true, "note": "repro gone on main"}}]}}"#
        );
        uc(Arc::clone(&store), &out)
            .execute()
            .await
            .expect("test pass runs");
        let state = store.load().await.expect("load");
        let t = state
            .tickets
            .iter()
            .find(|t| t.id().as_str() == "BUG-F024")
            .expect("ticket kept");
        t.test_cases()
            .iter()
            .find(|tc| tc.description == AC)
            .expect("the criterion's own test case")
            .status
    }

    #[tokio::test]
    async fn ac2_exact_criterion_text_still_lands_the_verdict() {
        // Baseline that already works and must keep working.
        assert_eq!(case_status_after_verdict(AC).await, TestCaseStatus::Passed);
    }

    #[tokio::test]
    async fn ac2_near_identical_wording_within_fuzzy_threshold_lands_the_verdict() {
        // One word dropped: normalized Levenshtein distance is far below 0.3
        // and keyword overlap is total — the generated matrix must still mark
        // the criterion COVERED instead of dropping the verdict.
        let status =
            case_status_after_verdict("the bug can no longer be reproduced on fresh checkout")
                .await;
        assert_eq!(
            status,
            TestCaseStatus::Passed,
            "fuzzy (Levenshtein <= 0.3) match must land the verdict"
        );
    }

    #[tokio::test]
    async fn ac2_reordered_keyword_overlap_lands_the_verdict() {
        // The same keywords in a different order — the keyword-overlap half
        // of the scoring must match where raw string distance would not.
        let status =
            case_status_after_verdict("reproduced on a fresh checkout the bug can no longer be")
                .await;
        assert_eq!(
            status,
            TestCaseStatus::Passed,
            "keyword overlap must land the reordered verdict"
        );
    }

    #[tokio::test]
    async fn ac2_unrelated_verdict_text_never_marks_a_criterion_covered() {
        // The threshold cuts both ways: a verdict about something else must
        // not flip this criterion to COVERED — over-eager fuzzy matching
        // would make the matrix lie.
        assert_eq!(
            case_status_after_verdict("the billing invoice totals are rounded incorrectly").await,
            TestCaseStatus::Pending,
            "unrelated verdict text must not cover the criterion"
        );
    }

    #[tokio::test]
    async fn ac2_only_the_matched_criterion_is_touched() {
        // The verdict addresses one criterion; the other stays NOT TESTED —
        // one verdict, one matrix row.
        let store = Arc::new(MemStore {
            state: Mutex::new(fixed_bug_state()),
        });
        let out = format!(
            r#"{{"bugs": [], "verdicts": [{{"ac": "{AC}", "passed": true, "note": "repro gone on main"}}]}}"#
        );
        uc(Arc::clone(&store), &out)
            .execute()
            .await
            .expect("test pass runs");
        let state = store.load().await.expect("load");
        let t = state
            .tickets
            .iter()
            .find(|t| t.id().as_str() == "BUG-F024")
            .expect("ticket kept");
        assert_eq!(t.test_cases().len(), 2, "one case per criterion, no more");
        let other = t
            .test_cases()
            .iter()
            .find(|tc| tc.description == AC_OTHER)
            .expect("the other criterion keeps its case");
        assert_eq!(other.status, TestCaseStatus::Pending);
    }
}
