//! TDD contract for CXA-F024 ("Test-to-AC Traceability Matrix"), part 2 of 2:
//! the acceptance criteria that need NEW domain surface.
//!
//! Part 1 (`verified_gate_f024.rs`) pins AC#3 and AC#4 against currently-shipped
//! API. This file pins AC#1, AC#2 and AC#5 against the coverage module CXA-F024
//! must add, so it is RED today until that module lands -- mirroring how
//! `config_drift_gate.rs` pinned types before CXA-F021 shipped them.
//
//// Minimal public additions required to turn this green:
////   A. `coxagent_domain::coverage` exposing
////        enum CoverageStatus { Covered, NotTested, PartiallyCovered }
////        struct CoverageEntry {
////            pub ac: String,
////            pub status: CoverageStatus,
////            pub covering_tests: Vec<String>,
////            pub covering_api_calls: Vec<String>,
////        }
//
////   B. A generator used once TEST completes verification (AC#2):
////        pub fn generate_coverage(
////            ac_texts: &[String],          // ticket.acceptance_criteria()
////            tester_outputs: &[String],    // TEST descriptions + assertions (+ tags)
////        ) -> Vec<CoverageEntry>
//
////      Ranking uses KEYWORD overlap OR FUZZY overlap -- normalized Levenshtein
////      distance <= 0.3 counts as an overlap (AC#2). Provenance tags on a tester
////      output steer which list is credited:
////          "\n#T tests/foo.rs" -> covering_tests     (file-based test link)
////          "\n#A POST /api/x"  -> covering_api_calls (request/response; no file) (AC#5)
//
use coxagent_domain::{Complexity, Priority, Role, Status, TechnicalDesign};
use coxagent_domain::{TicketId};
use coxagent_domain::{Ticket};
use coxagent_domain::{TicketType};

fn tid(s: &str) -> TicketId {
    TicketId::new(s).expect("valid id")
}

/// A feature whose technical design satisfies DoR and reaches Ready without UX.
fn ready_feature(id: &str) -> Ticket {
    let mut t = Ticket::new(
        tid(id),
        TicketType::Feature,
        "feature",
        "desc",
        Priority::Medium,
        Complexity::Small,
        false,
    )
    .expect("new feature");
    t.set_technical_design(
        Role ::Sa ,
        TechnicalDesign { approach :"go".into() , ..TechnicalDesign ::default() },
    )
    .expect("set tech design");
    t.transition_to(Role ::Sa ,Status ::Ready ).expect("ready");
    t
}

/// Mark every acceptance criterion's test case as passing.
fn mark_all_passed(t: &mut Ticket) {
    t.ensure_test_cases_from_acceptance();
    for ac in t.acceptance_criteria().to_vec() {
        assert!(t.set_test_case_result(&ac, true, None, None, "t".into()));
    }
}

/// AC#1 -- the ticket-detail Test Coverage tab shows each acceptance criterion
/// with its coverage status and the file(s) that address it. Encoded as the
/// requirement that a fully-verified ticket exposes one matrix row per
/// criterion, each carrying a status and covering-file list.
#[test]
fn ac1_matrix_lists_every_ac_with_status_and_covering_files() {
    let mut t = ready_feature("FEAT-F024-6");
    t.set_acceptance_criteria(vec![
        "login persists session".into(),
        "logout clears session".into(),
    ]);
    mark_all_passed(&mut t);
    let matrix = t.coverage_matrix();
    assert_eq!(matrix.len(), 2, "one coverage entry per acceptance criterion");
    for entry in &matrix {
        assert!(
            matches!(entry.status, coxagent_domain::coverage::CoverageStatus::Covered),
            "both criteria verified end-to-end are COVERED"
        );
        assert!(
            !entry.covering_tests.is_empty(),
            "the covering test file(s) for the criterion are listed"
        );
    }
}

/// AC#2 -- after TEST completes verification the matrix is auto-generated by
/// matching test descriptions/assertions against the ticket's acceptance-criteria
/// text using keyword + fuzzy (Levenshtein <= 0.3) overlap.
#[test]
fn ac2_keyword_overlap_marks_a_criterion_covered() {
    use coxagent_domain::coverage::{generate_coverage, CoverageStatus};
    let rows = generate_coverage(
        &["POST /api/inbox accepts valid payload".to_string()],
        &["post /api/inbox accepts a valid json payload (tests/api_inbox.rs)".to_string()],
    );
    assert_eq!(rows[0].status, CoverageStatus ::Covered);
}

/// AC#2 -- a near-paraphrase within normalized Levenshtein distance <= 0.3 is a
/// fuzzy overlap and must count as covered even without an exact keyword hit.
#[test]
fn ac2_fuzzy_overlap_within_point3_counts_as_covered() {
    use coxagent_domain::coverage::{generate_coverage, CoverageStatus};
    let rows = generate_coverage(
        &["The user can reset their password".to_string()],
        &["a user resets a forgotten password and can log back in (#T tests/auth_reset.rs)".to_string()],
    );
    assert_eq!(rows[0].status, CoverageStatus ::Covered);
    assert!(
        rows[0].covering_tests.iter().any(|f| f.contains("auth_reset.rs")),
        "the #T tag credits a file-based test link"
    );
}

/// AC#2 -- an unrelated tester output must leave the criterion NOT TESTED.
#[test]
fn ac2_unrelated_output_stays_not_tested() {
    use coxagent_domain::coverage::{generate_coverage, CoverageStatus};
    let rows = generate_coverage(
        &["The user can reset their password".to_string()],
        &["login button is vertically centered (tests/ui_login.rs)".to_string()],
    );
    assert_eq!(rows[0].status, CoverageStatus ::NotTested);
}

/// AC#5 -- for a non-UI ticket whose evidence is request/response, the matrix
/// credits the API call as covering the affected criteria rather than requiring
/// a file-based test link.
#[test]
fn ac5_nonui_request_response_is_credited_without_a_file_link() {
    use coxagent_domain::coverage::{generate_coverage, CoverageStatus};
    let rows = generate_coverage(
        &["GET /api/reports returns 200 with JSON".to_string()],
        &["request: GET /api/reports -> response: 200 application/json (#A GET /api/reports)".to_string()],
    );
    assert_eq!(rows[0].status, CoverageStatus ::Covered);
    assert!(
        rows[0].covering_tests.is_empty(),
        "a non-UI request/response ticket must NOT require a file-based test link"
    );
    assert!(
        rows[0].covering_api_calls.iter().any(|c| c.contains("GET /api/reports")),
        "the #A tag credits the API call as the covering evidence"
    );
}
